/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.awt.Container;
import javafx.scene.Parent;
import javax.swing.JTextField;

/**
 *
 * @author Juan Eduardo
 */
public class MatrixPanel extends javax.swing.JFrame {

    /**
     * Creates new form MatrixPanel
     */
    public  double[][] convM = new double[3][3];
    public int kernelDiv;
    private JTextField [][] values;
    public MatrixPanel(double[][] matrix,int divisor) {
        initComponents();
        createTextFields();
        convM = matrix;
        kernelDiv = divisor;
    }

    private MatrixPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApplyMatrix = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDivisor = new javax.swing.JTextField();
        btnGaussianBlur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnApplyMatrix.setText("Apply");
        btnApplyMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyMatrixActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        jLabel1.setText("Set Kernel");

        txtDivisor.setText("1");

        btnGaussianBlur.setText("Blur");
        btnGaussianBlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaussianBlurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDivisor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnApplyMatrix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGaussianBlur)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(txtDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnApplyMatrix)
                .addGap(37, 37, 37)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnGaussianBlur)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyMatrixActionPerformed
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                convM[i][j] = Double.valueOf(values[i][j].getText());
            }
        }
        kernelDiv = Integer.valueOf(txtDivisor.getText());
        this.dispose();
    }//GEN-LAST:event_btnApplyMatrixActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnGaussianBlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaussianBlurActionPerformed
       int[][] gblur = {{1,4,6,4,1},
                        {4,16,24,16,4},
                        {6,24,36,24,6},
                        {4,16,24,16,4},
                        {1,4,6,4,1}};
       
        for (int i = 0; i < gblur[0].length; i++) {
            for (int j = 0; j < gblur[0].length; j++) {
                values[i][j].setText(String.valueOf(gblur[i][j]));
            }
            
        }
       
    }//GEN-LAST:event_btnGaussianBlurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyMatrix;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGaussianBlur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDivisor;
    // End of variables declaration//GEN-END:variables

    private void createTextFields() {
        values = new JTextField[3][3];
        Container c = getContentPane();
        
        int x=45,y=50;
        for (int i = 0; i < 3; i++) {
            x=45;
            for (int j = 0; j < 3; j++) {
               values[i][j] = new JTextField("0");
               values[i][j].setBounds(x, y, 40, 30);
               values[i][j].setVisible(true);
               c.add(values[i][j]);
                x+=50;
            }
            y+=40;
        }
    }
}
